#page title
page_title                                : Mental Friend App                       # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : com.lelepepe.mentalfriend                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : il                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://expo.dev/artifacts/eas/eBfLYJHyrMRHXdEJyawewR.ipa
                                       # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :  https://expo.dev/artifacts/eas/shzqx4it8GfojRcKPNRQ5E.aab
                                         # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Mental health tracker for all

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Neuro Lena                                
your_link                                 : https://github.com/neuroLena                   
your_city                                 : Tel Aviv                                
email_address                             : mentalfriendtest@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : neuroLena
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Your Privacy Matters
    description                           : With all calculations handled on your device, your information stays with you. No email, phone number or name required! Simply set a nickname and password to start using the app. Your privacy is our commitment.
    fontawesome_icon_name                 : shield

  - title                                 : Customizable tracker
    description                           : Track What Matters to You - from symptoms and medications to habits and personal factors, our tracker is tailored to you.
    fontawesome_icon_name                 : magic
    
  - title                                 : Empower Yourself with Selfhelp
    description                           : Discover verified tips, tricks, and skill programs to manage and overcome a wide range of complications.
    fontawesome_icon_name                 : superpowers

  - title                                 : Unlock Insights Through Data
    description                           : Dive into data-driven insights and recommendations designed to support your unique journey
    fontawesome_icon_name                 : lightbulb

  - title                                 : Crisis Support When You Need It Most
    description                           : AI-powered alerts for critical states and comprehensive assistance to help you navigate through them.
    fontawesome_icon_name                 : hand

  - title                                 : Find Your Community and Social Support 
    description                           : Engage in meaningful and supportive communication with peers who understand your experience.
    fontawesome_icon_name                 : user-group

  - title                                 : Explore Yourself with Questionnaires
    description                           : Utilize verified questionnaires on various topics to understand your situation more profoundly.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Heal Through Playing Games
    description                           : Enjoy games designed to teach coping skills and enhance your mental well-being.
    fontawesome_icon_name                 : gamepad

  - title                                 : Share Your Progress 
    description                           : Export and share your data reports with healthcare providers and loved ones for a unified approach.
    fontawesome_icon_name                 : arrow-alt-circle-down

  
  - title                                 : Stay Informed 
    description                           : Receive the latest scientific information relevant to your condition.
    fontawesome_icon_name                 : info


  - title                                 : Absolutely Free 
    description                           : We believe in empowering everyone with full access to all the features.
    fontawesome_icon_name                 : gift


  - title                                 : Let's Grow Together
    description                           : We're committed to enhancing our app with your feedback and insights. Join us in making a difference.
    fontawesome_icon_name                 : seedling

  # - title                                 : # New Feature Title
  #   description                           : # New Feature Description
  #   fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/pexels-photo.webp                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#97B0D7"
cover_overlay_transparency                : 0.9

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#97B0D7"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#97B0D7"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
